version: '2'
services:
  badgr-server:
    container_name: badgr-server
    image: alex-badgr-server:latest
    #    image: badgr-server:latest
#    command: uwsgi --ini /badgr_server/uwsgi.ini
    volumes:
#      - app.sock:/badgr_server/app.sock
      - badgr_server_api:/badgr_server
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - badgr
    depends_on:
      - "db"
      - "memcached"

  memcached:
    image: 'bitnami/memcached:latest'
    container_name: bager-memcached
    expose:
      - "11211"
    networks:
      - badgr

  db:
    image: mysql:5.6.39
    container_name: badgr-db
    volumes:
      - ./volumes/badgr_server_prod_db:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    expose:
      - "3306"
    networks:
      - badgr

  # this container runs nginx (webserver) and uses the uwsgi app.sock file from prod_api via a volume
  nginx:
    image: badgr-nginx:latest
    container_name: badgr-nginx
    volumes:
      - badgr_server_api:/badgr_server
    ports:
      - "8080:80"
    networks:
      - badgr
    depends_on:
      - "badgr-server"

  badgr-ui:
    image: badgr-ui:latest
    container_name: badgr-ui
    environment:
      API_BASE_URL: badgr-server
    ports:
      - "4200:4200"
    networks:
      - badgr
    depends_on:
      - "badgr-server"

networks:
  badgr:
    driver: bridge

volumes:
  badgr_server_api:
